#!/bin/bash
# Autor: Nikita Tserni
# Skripti nimi: kujund
# Kirjeldus: Skript küsib ridade arvu ja trükib vastava kujundi.

# b. Sisendi küsimine
read -p "Sisesta ridade arv: " RIDU

# c. Kujundi trükkimine
for (( i=RIDU; i>=1; i-- )); do
    if [ $i -gt 1 ]; then
        echo -n "- "
        for (( j=1; j<i; j++ )); do
            echo -n "* "
        done
        echo ""
    else
        echo "*"
    fi
done
