#!/bin/bash
# Autor: Nikita Tserni
# Skripti nimi: menu
# Kirjeldus: Skript kuvab söögi valiku menüü ning väljastab vastava kirjelduse vastavalt kasutaja valikule.

# b. Menüü kuvamine
echo "1) liha ja kartulid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"

# c. Valiku küsimine
read -p "Tee oma valik (1 või 2 või 3): " VALIK

# d. Vastuse väljastamine
case $VALIK in
    1)
        echo "Väga maitsev, aga jälgi oma tervist!"
        echo "Head isu!"
        ;;
    2)
        echo "Brititoit on maisev!"
        echo "Head isu!"
        ;;
    3)
        echo "Nii tervislik ja igav..."
        echo "Head isu!"
        ;;
    *)
        echo "Vigane valik!"
        ;;
esac

